name: Apache Taverna Server
vendor: Apache Software Foundation
maintainer:
	name: Apache Taverna (incubating)
	email: dev@taverna.incubator.apache.org
platform: "Java 8+, Tomcat 6, POSIX"
download: https://taverna.incubator.apache.org/download/server/
homepage: https://taverna.incubator.apache.org/documentation/server/
issues: https://issues.apache.org/jira/browse/TAVERNA/component/12326813
support-contact: users@taverna.incubator.apache.org
