/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:15:49 PM GMT 
//


package org.apache.taverna.server.usagerecord.xml.urf2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Open Grid Forum GFD.204 Usage Record type <code>JobUsageBlockType</code>
 * 
 * @see <a href="https://www.ogf.org/documents/GFD.204.pdf#section.6">GFD.204 section 6</a>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobUsageBlockType", propOrder = {
    "globalJobId",
    "localJobId",
    "jobName",
    "machineName",
    "submitHost",
    "submitType",
    "queue",
    "timeInstant",
    "serviceLevel",
    "status"
})
public class JobUsageBlockType {

    @XmlElement(name = "GlobalJobId")
    protected String globalJobId;
    @XmlElement(name = "LocalJobId")
    protected String localJobId;
    @XmlElement(name = "JobName")
    protected String jobName;
    @XmlElement(name = "MachineName")
    protected String machineName;
    @XmlElement(name = "SubmitHost")
    protected String submitHost;
    @XmlElement(name = "SubmitType")
    protected SubmitTypeType submitType;
    @XmlElement(name = "Queue")
    protected QueueType queue;
    @XmlElement(name = "TimeInstant")
    protected List<TimeInstantType> timeInstant;
    @XmlElement(name = "ServiceLevel")
    protected String serviceLevel;
    @XmlElement(name = "Status", required = true)
    protected String status;

    /**
     * Gets the value of the globalJobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalJobId() {
        return globalJobId;
    }

    /**
     * Sets the value of the globalJobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalJobId(String value) {
        this.globalJobId = value;
    }

    /**
     * Gets the value of the localJobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalJobId() {
        return localJobId;
    }

    /**
     * Sets the value of the localJobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalJobId(String value) {
        this.localJobId = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    /**
     * Gets the value of the submitHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitHost() {
        return submitHost;
    }

    /**
     * Sets the value of the submitHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitHost(String value) {
        this.submitHost = value;
    }

    /**
     * Gets the value of the submitType property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitTypeType }
     *     
     */
    public SubmitTypeType getSubmitType() {
        return submitType;
    }

    /**
     * Sets the value of the submitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitTypeType }
     *     
     */
    public void setSubmitType(SubmitTypeType value) {
        this.submitType = value;
    }

    /**
     * Gets the value of the queue property.
     * 
     * @return
     *     possible object is
     *     {@link QueueType }
     *     
     */
    public QueueType getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueType }
     *     
     */
    public void setQueue(QueueType value) {
        this.queue = value;
    }

    /**
     * Gets the value of the timeInstant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeInstant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeInstant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeInstantType }
     * 
     * 
     */
    public List<TimeInstantType> getTimeInstant() {
        if (timeInstant == null) {
            timeInstant = new ArrayList<TimeInstantType>();
        }
        return this.timeInstant;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevel(String value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
