/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:15:49 PM GMT 
//
/**
 * Open Grid Forum GFD.204 Usage Record Format JAXB elements.
 * <p>
 * JAXB beans for the <em>Usage Record Format 2.0</em> as described by
 * <a href="Open Grid Forum">https://www.ogf.org/</a> (OGF) specification
 * <a href="https://www.ogf.org/documents/GFD.204.pdf">GFD.204</a> serialized in
 * the namespace <code>http://schema.ogf.org/urf/2013/04/urf</code>
 * <p>
 * This package provides the underlying JAXB elements and types for marshalling
 * and unmarshalling XML according to the Usage Record Format.
 * <p>
 * The classes in this package are derived from the XML schema in
 * <a href="https://www.ogf.org/documents/GFD.204.pdf#section.14">
 * GDF.204 section 14</a>
 * <p>
 * <blockquote>Copyright © Open Grid Forum (2006-2013). Some Rights Reserved.
 * <p>
 * This document and translations of it may be copied and furnished to others,
 * and derivative works that comment on or otherwise explain it or assist in its
 * implementation may be prepared, copied, published and distributed, in whole
 * or in part, without restriction of any kind, provided that the above
 * copyright notice and this paragraph are included as references to the derived
 * portions on all such copies and derivative works. The published OGF document
 * from which such works are derived, however, may not be modified in any way,
 * such as by removing the copyright notice or references to the OGF or other
 * organizations, except as needed for the purpose of developing new or updated
 * OGF documents in conformance with the procedures defined in the OGF Document
 * Process, or as required to translate it into languages other than English.
 * OGF, with the approval of its board, may remove this restriction for
 * inclusion of OGF document content for the purpose of producing standards in
 * cooperation with other international standards bodies.
 * <p>
 * The limited permissions granted above are perpetual and will not be revoked
 * by the OGF or its successors or assignees.
 * </blockquote>
 * 
 * @see <a href="https://www.ogf.org/documents/GFD.204.pdf">GFD.98</a>
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.ogf.org/urf/2013/04/urf", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.apache.taverna.server.usagerecord.xml.urf2;
