/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:15:49 PM GMT 
//


package org.apache.taverna.server.usagerecord.xml.urf2;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Open Grid Forum GFD.204 Usage Record type <code>StorageUsageBlockType</code>
 * 
 * @see <a href="https://www.ogf.org/documents/GFD.204.pdf#section.8">GFD.204 section 8</a>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageUsageBlockType", propOrder = {
    "storageShare",
    "storageMedia",
    "storageClass",
    "directoryPath",
    "fileCount",
    "storageResourceCapacityUsed",
    "storageLogicalCapacityUsed",
    "storageResourceCapacityAllocated",
    "startTime",
    "endTime",
    "host",
    "hostType",
    "charge"
})
public class StorageUsageBlockType {

    @XmlElement(name = "StorageShare")
    protected String storageShare;
    @XmlElement(name = "StorageMedia")
    protected String storageMedia;
    @XmlElement(name = "StorageClass")
    protected String storageClass;
    @XmlElement(name = "DirectoryPath")
    protected String directoryPath;
    @XmlElement(name = "FileCount")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger fileCount;
    @XmlElement(name = "StorageResourceCapacityUsed", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger storageResourceCapacityUsed;
    @XmlElement(name = "StorageLogicalCapacityUsed")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger storageLogicalCapacityUsed;
    @XmlElement(name = "StorageResourceCapacityAllocated")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger storageResourceCapacityAllocated;
    @XmlElement(name = "StartTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "EndTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "Host")
    protected String host;
    @XmlElement(name = "HostType")
    protected String hostType;
    @XmlElement(name = "Charge")
    protected BigDecimal charge;

    /**
     * Gets the value of the storageShare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageShare() {
        return storageShare;
    }

    /**
     * Sets the value of the storageShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageShare(String value) {
        this.storageShare = value;
    }

    /**
     * Gets the value of the storageMedia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageMedia() {
        return storageMedia;
    }

    /**
     * Sets the value of the storageMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageMedia(String value) {
        this.storageMedia = value;
    }

    /**
     * Gets the value of the storageClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageClass() {
        return storageClass;
    }

    /**
     * Sets the value of the storageClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageClass(String value) {
        this.storageClass = value;
    }

    /**
     * Gets the value of the directoryPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryPath() {
        return directoryPath;
    }

    /**
     * Sets the value of the directoryPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryPath(String value) {
        this.directoryPath = value;
    }

    /**
     * Gets the value of the fileCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFileCount() {
        return fileCount;
    }

    /**
     * Sets the value of the fileCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFileCount(BigInteger value) {
        this.fileCount = value;
    }

    /**
     * Gets the value of the storageResourceCapacityUsed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStorageResourceCapacityUsed() {
        return storageResourceCapacityUsed;
    }

    /**
     * Sets the value of the storageResourceCapacityUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStorageResourceCapacityUsed(BigInteger value) {
        this.storageResourceCapacityUsed = value;
    }

    /**
     * Gets the value of the storageLogicalCapacityUsed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStorageLogicalCapacityUsed() {
        return storageLogicalCapacityUsed;
    }

    /**
     * Sets the value of the storageLogicalCapacityUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStorageLogicalCapacityUsed(BigInteger value) {
        this.storageLogicalCapacityUsed = value;
    }

    /**
     * Gets the value of the storageResourceCapacityAllocated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStorageResourceCapacityAllocated() {
        return storageResourceCapacityAllocated;
    }

    /**
     * Sets the value of the storageResourceCapacityAllocated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStorageResourceCapacityAllocated(BigInteger value) {
        this.storageResourceCapacityAllocated = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the hostType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostType() {
        return hostType;
    }

    /**
     * Sets the value of the hostType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostType(String value) {
        this.hostType = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCharge(BigDecimal value) {
        this.charge = value;
    }

}
