/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:15:49 PM GMT 
//


package org.apache.taverna.server.usagerecord.xml.urf2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Open Grid Forum GFD.204 Usage Record type <code>UsageRecordType</code>
 * 
 * @see <a href="https://www.ogf.org/documents/GFD.204.pdf#section.13">GFD.204 section 13</a>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsageRecordType", propOrder = {
    "recordIdentityBlock",
    "subjectIdentityBlock",
    "computeUsageBlock",
    "jobUsageBlock",
    "memoryUsageBlock",
    "storageUsageBlock",
    "cloudUsageBlock",
    "networkUsageBlock"
})
public class UsageRecordType {

    @XmlElement(name = "RecordIdentityBlock", required = true)
    protected RecordIdentityBlockType recordIdentityBlock;
    @XmlElement(name = "SubjectIdentityBlock")
    protected SubjectIdentityBlockType subjectIdentityBlock;
    @XmlElement(name = "ComputeUsageBlock")
    protected List<ComputeUsageBlockType> computeUsageBlock;
    @XmlElement(name = "JobUsageBlock")
    protected JobUsageBlockType jobUsageBlock;
    @XmlElement(name = "MemoryUsageBlock")
    protected List<MemoryUsageBlockType> memoryUsageBlock;
    @XmlElement(name = "StorageUsageBlock")
    protected List<StorageUsageBlockType> storageUsageBlock;
    @XmlElement(name = "CloudUsageBlock")
    protected CloudUsageBlockType cloudUsageBlock;
    @XmlElement(name = "NetworkUsageBlock")
    protected List<NetworkUsageBlockType> networkUsageBlock;

    /**
     * Gets the value of the recordIdentityBlock property.
     * 
     * @return
     *     possible object is
     *     {@link RecordIdentityBlockType }
     *     
     */
    public RecordIdentityBlockType getRecordIdentityBlock() {
        return recordIdentityBlock;
    }

    /**
     * Sets the value of the recordIdentityBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordIdentityBlockType }
     *     
     */
    public void setRecordIdentityBlock(RecordIdentityBlockType value) {
        this.recordIdentityBlock = value;
    }

    /**
     * Gets the value of the subjectIdentityBlock property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentityBlockType }
     *     
     */
    public SubjectIdentityBlockType getSubjectIdentityBlock() {
        return subjectIdentityBlock;
    }

    /**
     * Sets the value of the subjectIdentityBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentityBlockType }
     *     
     */
    public void setSubjectIdentityBlock(SubjectIdentityBlockType value) {
        this.subjectIdentityBlock = value;
    }

    /**
     * Gets the value of the computeUsageBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the computeUsageBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComputeUsageBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComputeUsageBlockType }
     * 
     * 
     */
    public List<ComputeUsageBlockType> getComputeUsageBlock() {
        if (computeUsageBlock == null) {
            computeUsageBlock = new ArrayList<ComputeUsageBlockType>();
        }
        return this.computeUsageBlock;
    }

    /**
     * Gets the value of the jobUsageBlock property.
     * 
     * @return
     *     possible object is
     *     {@link JobUsageBlockType }
     *     
     */
    public JobUsageBlockType getJobUsageBlock() {
        return jobUsageBlock;
    }

    /**
     * Sets the value of the jobUsageBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobUsageBlockType }
     *     
     */
    public void setJobUsageBlock(JobUsageBlockType value) {
        this.jobUsageBlock = value;
    }

    /**
     * Gets the value of the memoryUsageBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memoryUsageBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemoryUsageBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemoryUsageBlockType }
     * 
     * 
     */
    public List<MemoryUsageBlockType> getMemoryUsageBlock() {
        if (memoryUsageBlock == null) {
            memoryUsageBlock = new ArrayList<MemoryUsageBlockType>();
        }
        return this.memoryUsageBlock;
    }

    /**
     * Gets the value of the storageUsageBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storageUsageBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorageUsageBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StorageUsageBlockType }
     * 
     * 
     */
    public List<StorageUsageBlockType> getStorageUsageBlock() {
        if (storageUsageBlock == null) {
            storageUsageBlock = new ArrayList<StorageUsageBlockType>();
        }
        return this.storageUsageBlock;
    }

    /**
     * Gets the value of the cloudUsageBlock property.
     * 
     * @return
     *     possible object is
     *     {@link CloudUsageBlockType }
     *     
     */
    public CloudUsageBlockType getCloudUsageBlock() {
        return cloudUsageBlock;
    }

    /**
     * Sets the value of the cloudUsageBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudUsageBlockType }
     *     
     */
    public void setCloudUsageBlock(CloudUsageBlockType value) {
        this.cloudUsageBlock = value;
    }

    /**
     * Gets the value of the networkUsageBlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkUsageBlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkUsageBlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkUsageBlockType }
     * 
     * 
     */
    public List<NetworkUsageBlockType> getNetworkUsageBlock() {
        if (networkUsageBlock == null) {
            networkUsageBlock = new ArrayList<NetworkUsageBlockType>();
        }
        return this.networkUsageBlock;
    }

}
