/*
 * Copyright (C) 2011 The University of Manchester
 * 
 * See the file "LICENSE" for license terms.
 */
package org.taverna.server.master.notification.atom;

import static javax.ws.rs.core.UriBuilder.fromUri;
import static org.taverna.server.master.common.Roles.USER;

import java.net.URI;
import java.util.List;

import javax.annotation.security.RolesAllowed;
import javax.servlet.ServletContext;
import javax.ws.rs.core.UriBuilder;

import org.springframework.web.context.ServletContextAware;
import org.taverna.server.master.TavernaServerSupport;
import org.taverna.server.master.ContentsDescriptorBuilder.UriBuilderFactory;
import org.taverna.server.master.interfaces.TavernaRun;
import org.taverna.server.master.rest.TavernaServerREST.EventFeed;
import org.taverna.server.master.rest.TavernaServerREST.Events;
import org.taverna.server.master.utils.UsernamePrincipal;
import org.taverna.server.master.utils.InvocationCounter.CallCounted;

import edu.umd.cs.findbugs.annotations.NonNull;

/**
 * Simple REST handler that allows an Atom feed to be served up of events
 * generated by workflow runs.
 * 
 * @author Donal Fellows
 */
public class AtomFeed implements EventFeed, UriBuilderFactory,
		ServletContextAware {
	/**
	 * The name of a parameter that states what address we should claim that the
	 * feed's internally-generated URIs are relative to. If not set, a default
	 * will be guessed.
	 */
	public static final String PREFERRED_URI_PARAM = "taverna.preferredUserUri";
	private EventDAO eventSource;
	private TavernaServerSupport support;
	private URI baseURI;
	private String feedLanguage = "en";

	public void setEventSource(EventDAO eventSource) {
		this.eventSource = eventSource;
	}

	public void setSupport(TavernaServerSupport support) {
		this.support = support;
	}

	public void setFeedLanguage(String language) {
		this.feedLanguage = language;
	}

	public String getFeedLanguage() {
		return feedLanguage;
	}

	/**
	 * The implementation of a feed of events for a workflow run.
	 * 
	 * @author Donal Fellows
	 */
	public static class Feed extends Events {
		private UsernamePrincipal owner;
		private EventDAO eventSource;

		Feed(@NonNull EventDAO eventSource, @NonNull UsernamePrincipal owner) {
			this.eventSource = eventSource;
			this.owner = owner;
		}

		@Override
		public String getOwner() {
			return owner.getName();
		}

		@Override
		public List<AbstractEvent> getEvents() {
			return eventSource.getEvents(owner);
		}

		@Override
		public AbstractEvent getEvent(String id) {
			return eventSource.getEvent(owner, id);
		}
	}

	@Override
	@CallCounted
	@RolesAllowed(USER)
	public Events getFeed() {
		return new Feed(eventSource, support.getPrincipal());
	}

	@Override
	@CallCounted
	@RolesAllowed(USER)
	public AbstractEvent getEvent(String id) {
		return eventSource.getEvent(support.getPrincipal(), id);
	}

	@Override
	public UriBuilder getRunUriBuilder(TavernaRun run) {
		return fromUri(getBaseUriBuilder().path("runs/{uuid}").build(
				run.getId()));
	}

	@Override
	public UriBuilder getBaseUriBuilder() {
		return fromUri(baseURI);
	}

	@Override
	public String resolve(String uri) {
		return baseURI.resolve(uri).toString();
	}

	@Override
	public void setServletContext(ServletContext servletContext) {
		String base = servletContext.getInitParameter(PREFERRED_URI_PARAM);
		if (base == null)
			baseURI = URI.create(servletContext.getContextPath() + "/rest");
		else
			baseURI = URI.create(base);
	}
}
